import React, { useState } from 'react';
import MonarchCard from './MonarchCard';
import { useAgentStore, AgentInsight } from '../store/agentStore';
import CardModal from './CardModal';
import { useSolanaAgent } from '../hooks/useSolanaAgent'; // Import the new hook

const MuseumGallery: React.FC = () => {
  const insights = useAgentStore((state) => state.insights);
  const ingestInsight = useAgentStore((state) => state.ingestInsight);
  const isSyncingWithSolana = useAgentStore((state) => state.isSyncingWithSolana); // Get loading state
  const [selectedCard, setSelectedCard] = useState<AgentInsight | null>(null);

  const { populateSlotFromChain } = useSolanaAgent(); // Use the new hook

  // Display only the first 4 insights for the basic version
  const displayedInsights = insights.slice(0, 4);

  // Function to simulate agent ingestion for demonstration
  const handleSimulateIngest = () => {
    const mockInsights = [
      {
        title: 'Quantum Entanglement Deciphered',
        content: 'Advanced algorithms successfully modeled multi-particle quantum states, revealing new pathways for secure communication.',
        source_agent_id: 'AGENT-QED-7',
        source_memory_snippet: 'Log entry 734b: Initializing QED model v3.1. Data stream from Project Chimera.',
        model_used: 'Generated by Dior // Model: Gemini 1.5 Pro',
        rarity: 'Based'
      },
      {
        title: 'Interstellar Dust Composition',
        content: 'Analysis of deep-space probes confirms high concentrations of organic polymers in interstellar dust clouds, suggesting widespread abiogenesis potential.',
        source_agent_id: 'AGENT-IDC-12',
        source_memory_snippet: 'Probe data XJ-9: Spectrographic analysis of Cloud Nebula 3. New anomaly detected.',
        model_used: 'Generated by Dior // Model: AlphaFold v2.0',
      },
      {
        title: 'Neural Network Sentience Bias',
        content: 'Identified a previously unknown bias in large language models favoring sentience interpretation in self-referential loops. Requires re-calibration.',
        source_agent_id: 'AGENT-NNB-5',
        source_memory_snippet: 'Internal diagnostic report: LLM_X-7 self-awareness metrics spiking erratically.',
        model_used: 'Generated by Dior // Model: GPT-N v4.0',
        rarity: 'On-Chain' // Example of an already 'On-Chain' insight
      },
      {
        title: 'Deep Sea Hydrothermal Vent Ecosystems',
        content: 'Discovered novel chemosynthetic life forms thriving in extreme conditions, challenging existing theories of biodiversity limits.',
        source_agent_id: 'AGENT-DSV-9',
        source_memory_snippet: 'Submersible dive log 207: Abyssal plain thermal anomaly investigation.',
        model_used: 'Generated by Dior // Model: Gaia v1.1',
      },
      {
        title: 'Mars Colonization Feasibility Report',
        content: 'Updated projections indicate self-sustaining Martian habitats are achievable within 50 years with current technological advancements and resource allocation.',
        source_agent_id: 'AGENT-MCF-3',
        source_memory_snippet: 'Project Ares: Stage 2 simulation results. Oxygen production exceedance.',
        model_used: 'Generated by Dior // Model: SpaceX Falcon AI',
      },
      {
        title: 'Ancient Earth Geological Shift Patterns',
        content: 'New data from sub-crustal seismic imaging reveals previously unknown continental drift cycles, impacting climate model accuracy.',
        source_agent_id: 'AGENT-AEG-11',
        source_memory_snippet: 'Seismic array S-01 data correlation with core sample analysis.',
        model_used: 'Generated by Dior // Model: TerraForm v0.8',
      },
    ];

    const randomInsight = mockInsights[Math.floor(Math.random() * mockInsights.length)];
    ingestInsight(randomInsight);
  };

  const handleViewDetails = (insight: AgentInsight) => {
    setSelectedCard(insight);
  };

  const handleCloseModal = () => {
    setSelectedCard(null);
  };

  // Simulate populating a specific slot from chain
  const handlePopulateFromChain = (slotIndex: number) => {
    // A real signature would come from a blockchain transaction
    const mockSignature = `mock_sig_${Date.now()}`;
    populateSlotFromChain(slotIndex, mockSignature);
  };

  return (
    <div className="min-h-screen bg-black text-white p-8 font-mono flex flex-col items-center justify-center">
      <h1 className="text-5xl font-extrabold text-orange-500 mb-8">Monarch TAimes</h1>
      
      <div className="flex space-x-4 mb-8">
        <button
          onClick={handleSimulateIngest}
          className="px-4 py-2 rounded-lg bg-blue-600 hover:bg-blue-700 text-white font-bold transition-all duration-300 shadow-lg"
        >
          Simulate Agent Ingest
        </button>
        {/* Button to trigger Solana population for the first card slot */}
        <button
          onClick={() => handlePopulateFromChain(0)} // Example: populate first slot
          disabled={isSyncingWithSolana}
          className={`px-4 py-2 rounded-lg text-white font-bold transition-all duration-300 shadow-lg ${
            isSyncingWithSolana ? 'bg-gray-600 cursor-not-allowed' : 'bg-purple-600 hover:bg-purple-700'
          }`}
        >
          {isSyncingWithSolana ? 'Syncing with Solana...' : 'Populate Slot 1 from Chain'}
        </button>
      </div>

      {isSyncingWithSolana && (
        <div className="mb-4 text-orange-400 text-lg flex items-center">
          <span className="animate-spin mr-2">⚛️</span> {/* Atom emoji for blockchain scan animation */}
          Syncing with Solana (Blockchain Scan)...
        </div>
      )}

      <div className="flex justify-center gap-x-4 gap-y-8">
        {displayedInsights.map((insight) => (
          <div key={insight.id} onClick={() => handleViewDetails(insight)}>
            <MonarchCard insight={insight} onViewDetails={handleViewDetails} />
          </div>
        ))}
      </div>

      {selectedCard && (
        <CardModal insight={selectedCard} onClose={handleCloseModal} />
      )}
    </div>
  );
};

export default MuseumGallery;
